### ISSUE TITLE
Implement class spec in yaml

### ISSUE THREAD

**Issue by mpadge** [mpadge/autotest#1]
It will be useful/necessary to indicate whether a function expects input objects to conform to some particular class(es), which will be possible through parsing additional `yaml` lines like these:

```
package: <package_name>
functions:
    - <name of function>:
        - preprocess:
            - "<R code required for pre-processing exlosed in quotation marks>"
            - "<second line of pre-processing code>"
            - "<more code>"
        - class:
            - <param_name>: <class_type>
        - parameters:
            - <param_name>: <value>
            - <another_param>: <value>
```
